### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by kozora** [lzyyauto/efb2w#5]
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 267, in main
    init(conf)
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 91, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 174, in __init__
    self.authenticate('console_qr_code')
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 521, in authenticate
    logout_callback=self.exit_callback)
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/wxpy/api/bot.py", line 97, in __init__
    enhance_webwx_request(self)
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/wxpy/utils/misc.py", line 327, in enhance_webwx_request
    '&pass_ticket={li[pass_ticket]}'.format(li=login_info)
KeyError: 'wxsid'

**Comment by yemoke** [comment]
一样的错误正在找解决方案

**Comment by gagadesu** [comment]
遇到一样的错误

**Comment by maxsky** [comment]
same error
